Table Dificultad {
	idDificultad integer [ pk, increment, not null, unique ]
	nombreDificultad integer [ not null ]
}

Table Marca {
	idMarca integer [ pk, not null, unique ]
	nombreMarca varchar [ not null ]
}

Table ProcesoPlanta {
	idProcesoPlanta integer [ pk, increment, not null, unique ]
	plantaColor varchar [ not null ]
	idProceso integer [ not null ]
}

Table Procesos {
	idProcesos integer [ pk, not null, unique ]
	nombreProceso varchar [ not null ]
	idDificultad integer [ not null ]
}

Table Plantas {
	colorPlanta varchar [ pk, not null, unique ]
	nombrePlanta varchar [ not null ]
	superficie decimal [ not null ]
}

Table Tecnico {
	dni integer [ pk, increment, not null, unique ]
	nombreTecnico varchar [ not null ]
	apellidoTecnico1 varchar [ not null ]
	apellidoTecnico2 varchar [ not null ]
	fechaNacimiento integer [ not null ]
	telefonoTecnico1 varchar [ not null ]
	telefonoTecnico2 varchar
	telefonoTecnico3 varchar
}

Table Asignaciones {
	idAsignacion integer [ pk, increment, not null, unique ]
	maquinaPrincipal integer [ not null ]
	maquinaSecundaria integer [ not null ]
	dniTecnicoi integer [ not null ]
	idTurno integer [ not null ]
	fechaInicio integer [ not null ]
	fechaFinal integer [ not null ]
}

Table Maquina {
	idMaquina integer [ pk, increment, not null, unique ]
	idMarca integer [ not null ]
	modeloMaquina varchar [ not null ]
	noSerie varchar [ not null ]
	idProcesoPlanta integer [ not null ]
	idEstatus smallint [ not null ]
}

Table Turno {
	idTurno integer [ pk, increment, not null, unique ]
	nombreTurno varchar [ not null ]
	horaInicio integer [ not null ]
	horaFin integer [ not null ]
}

Table Estatus {
	idEstatus integer [ pk, increment, not null, unique ]
	nombreEstatus varchar [ not null ]
}

Ref fk_plantas_color_planta_proceso_planta {
	Plantas.colorPlanta < ProcesoPlanta.plantaColor [ delete: no action, update: set null ]
}

Ref fk_procesos_id_procesos_proceso_planta {
	Procesos.idProcesos < ProcesoPlanta.idProceso [ delete: no action, update: set null ]
}

Ref fk_dificultad_id_dificultad_procesos {
	Dificultad.idDificultad < Procesos.idDificultad [ delete: no action, update: set null ]
}

Ref fk_marca_id_marca_maquina {
	Marca.idMarca < Maquina.idMarca [ delete: no action, update: no action ]
}

Ref fk_maquina_id_maquina_asignaciones {
	Maquina.idMaquina < Asignaciones.maquinaPrincipal [ delete: no action, update: no action ]
}

Ref fk_maquina_id_maquina_asignaciones {
	Maquina.idMaquina < Asignaciones.maquinaSecundaria [ delete: no action, update: no action ]
}

Ref fk_tecnico_dni_asignaciones {
	Tecnico.dni < Asignaciones.dniTecnicoi [ delete: no action, update: no action ]
}

Ref fk_turno_id_turno_asignaciones {
	Turno.idTurno < Asignaciones.idTurno [ delete: no action, update: no action ]
}

Ref fk_Estatus_idEstatus_Maquina {
	Estatus.idEstatus - Maquina.idEstatus [ delete: no action, update: no action ]
}

Ref fk_Maquina_idProcesoPlanta_ProcesoPlanta {
	Maquina.idProcesoPlanta - ProcesoPlanta.idProcesoPlanta [ delete: no action, update: no action ]
}